// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: config/config.proto

package config

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Config service

type ConfigService interface {
	CreateApp(ctx context.Context, in *App, opts ...client.CallOption) (*App, error)
	DeleteApp(ctx context.Context, in *App, opts ...client.CallOption) (*Response, error)
	ListApps(ctx context.Context, in *Request, opts ...client.CallOption) (*Apps, error)
	CreateCluster(ctx context.Context, in *Cluster, opts ...client.CallOption) (*Cluster, error)
	DeleteCluster(ctx context.Context, in *Cluster, opts ...client.CallOption) (*Response, error)
	ListClusters(ctx context.Context, in *App, opts ...client.CallOption) (*Clusters, error)
	CreateNamespace(ctx context.Context, in *Namespace, opts ...client.CallOption) (*Namespace, error)
	DeleteNamespace(ctx context.Context, in *Namespace, opts ...client.CallOption) (*Response, error)
	ListNamespaces(ctx context.Context, in *Cluster, opts ...client.CallOption) (*Namespaces, error)
	UpdateConfig(ctx context.Context, in *Namespace, opts ...client.CallOption) (*Response, error)
	ReleaseConfig(ctx context.Context, in *Release, opts ...client.CallOption) (*Response, error)
	Read(ctx context.Context, in *Namespaces, opts ...client.CallOption) (*Namespaces, error)
	Watch(ctx context.Context, in *Request, opts ...client.CallOption) (Config_WatchService, error)
}

type configService struct {
	c    client.Client
	name string
}

func NewConfigService(name string, c client.Client) ConfigService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "config"
	}
	return &configService{
		c:    c,
		name: name,
	}
}

func (c *configService) CreateApp(ctx context.Context, in *App, opts ...client.CallOption) (*App, error) {
	req := c.c.NewRequest(c.name, "Config.CreateApp", in)
	out := new(App)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configService) DeleteApp(ctx context.Context, in *App, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Config.DeleteApp", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configService) ListApps(ctx context.Context, in *Request, opts ...client.CallOption) (*Apps, error) {
	req := c.c.NewRequest(c.name, "Config.ListApps", in)
	out := new(Apps)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configService) CreateCluster(ctx context.Context, in *Cluster, opts ...client.CallOption) (*Cluster, error) {
	req := c.c.NewRequest(c.name, "Config.CreateCluster", in)
	out := new(Cluster)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configService) DeleteCluster(ctx context.Context, in *Cluster, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Config.DeleteCluster", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configService) ListClusters(ctx context.Context, in *App, opts ...client.CallOption) (*Clusters, error) {
	req := c.c.NewRequest(c.name, "Config.ListClusters", in)
	out := new(Clusters)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configService) CreateNamespace(ctx context.Context, in *Namespace, opts ...client.CallOption) (*Namespace, error) {
	req := c.c.NewRequest(c.name, "Config.CreateNamespace", in)
	out := new(Namespace)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configService) DeleteNamespace(ctx context.Context, in *Namespace, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Config.DeleteNamespace", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configService) ListNamespaces(ctx context.Context, in *Cluster, opts ...client.CallOption) (*Namespaces, error) {
	req := c.c.NewRequest(c.name, "Config.ListNamespaces", in)
	out := new(Namespaces)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configService) UpdateConfig(ctx context.Context, in *Namespace, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Config.UpdateConfig", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configService) ReleaseConfig(ctx context.Context, in *Release, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Config.ReleaseConfig", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configService) Read(ctx context.Context, in *Namespaces, opts ...client.CallOption) (*Namespaces, error) {
	req := c.c.NewRequest(c.name, "Config.Read", in)
	out := new(Namespaces)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configService) Watch(ctx context.Context, in *Request, opts ...client.CallOption) (Config_WatchService, error) {
	req := c.c.NewRequest(c.name, "Config.Watch", &Request{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &configServiceWatch{stream}, nil
}

type Config_WatchService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*Namespace, error)
}

type configServiceWatch struct {
	stream client.Stream
}

func (x *configServiceWatch) Close() error {
	return x.stream.Close()
}

func (x *configServiceWatch) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *configServiceWatch) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *configServiceWatch) Recv() (*Namespace, error) {
	m := new(Namespace)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Config service

type ConfigHandler interface {
	CreateApp(context.Context, *App, *App) error
	DeleteApp(context.Context, *App, *Response) error
	ListApps(context.Context, *Request, *Apps) error
	CreateCluster(context.Context, *Cluster, *Cluster) error
	DeleteCluster(context.Context, *Cluster, *Response) error
	ListClusters(context.Context, *App, *Clusters) error
	CreateNamespace(context.Context, *Namespace, *Namespace) error
	DeleteNamespace(context.Context, *Namespace, *Response) error
	ListNamespaces(context.Context, *Cluster, *Namespaces) error
	UpdateConfig(context.Context, *Namespace, *Response) error
	ReleaseConfig(context.Context, *Release, *Response) error
	Read(context.Context, *Namespaces, *Namespaces) error
	Watch(context.Context, *Request, Config_WatchStream) error
}

func RegisterConfigHandler(s server.Server, hdlr ConfigHandler, opts ...server.HandlerOption) error {
	type config interface {
		CreateApp(ctx context.Context, in *App, out *App) error
		DeleteApp(ctx context.Context, in *App, out *Response) error
		ListApps(ctx context.Context, in *Request, out *Apps) error
		CreateCluster(ctx context.Context, in *Cluster, out *Cluster) error
		DeleteCluster(ctx context.Context, in *Cluster, out *Response) error
		ListClusters(ctx context.Context, in *App, out *Clusters) error
		CreateNamespace(ctx context.Context, in *Namespace, out *Namespace) error
		DeleteNamespace(ctx context.Context, in *Namespace, out *Response) error
		ListNamespaces(ctx context.Context, in *Cluster, out *Namespaces) error
		UpdateConfig(ctx context.Context, in *Namespace, out *Response) error
		ReleaseConfig(ctx context.Context, in *Release, out *Response) error
		Read(ctx context.Context, in *Namespaces, out *Namespaces) error
		Watch(ctx context.Context, stream server.Stream) error
	}
	type Config struct {
		config
	}
	h := &configHandler{hdlr}
	return s.Handle(s.NewHandler(&Config{h}, opts...))
}

type configHandler struct {
	ConfigHandler
}

func (h *configHandler) CreateApp(ctx context.Context, in *App, out *App) error {
	return h.ConfigHandler.CreateApp(ctx, in, out)
}

func (h *configHandler) DeleteApp(ctx context.Context, in *App, out *Response) error {
	return h.ConfigHandler.DeleteApp(ctx, in, out)
}

func (h *configHandler) ListApps(ctx context.Context, in *Request, out *Apps) error {
	return h.ConfigHandler.ListApps(ctx, in, out)
}

func (h *configHandler) CreateCluster(ctx context.Context, in *Cluster, out *Cluster) error {
	return h.ConfigHandler.CreateCluster(ctx, in, out)
}

func (h *configHandler) DeleteCluster(ctx context.Context, in *Cluster, out *Response) error {
	return h.ConfigHandler.DeleteCluster(ctx, in, out)
}

func (h *configHandler) ListClusters(ctx context.Context, in *App, out *Clusters) error {
	return h.ConfigHandler.ListClusters(ctx, in, out)
}

func (h *configHandler) CreateNamespace(ctx context.Context, in *Namespace, out *Namespace) error {
	return h.ConfigHandler.CreateNamespace(ctx, in, out)
}

func (h *configHandler) DeleteNamespace(ctx context.Context, in *Namespace, out *Response) error {
	return h.ConfigHandler.DeleteNamespace(ctx, in, out)
}

func (h *configHandler) ListNamespaces(ctx context.Context, in *Cluster, out *Namespaces) error {
	return h.ConfigHandler.ListNamespaces(ctx, in, out)
}

func (h *configHandler) UpdateConfig(ctx context.Context, in *Namespace, out *Response) error {
	return h.ConfigHandler.UpdateConfig(ctx, in, out)
}

func (h *configHandler) ReleaseConfig(ctx context.Context, in *Release, out *Response) error {
	return h.ConfigHandler.ReleaseConfig(ctx, in, out)
}

func (h *configHandler) Read(ctx context.Context, in *Namespaces, out *Namespaces) error {
	return h.ConfigHandler.Read(ctx, in, out)
}

func (h *configHandler) Watch(ctx context.Context, stream server.Stream) error {
	m := new(Request)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.ConfigHandler.Watch(ctx, m, &configWatchStream{stream})
}

type Config_WatchStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Namespace) error
}

type configWatchStream struct {
	stream server.Stream
}

func (x *configWatchStream) Close() error {
	return x.stream.Close()
}

func (x *configWatchStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *configWatchStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *configWatchStream) Send(m *Namespace) error {
	return x.stream.Send(m)
}
